### ISSUE TITLE
Plex Playing

### ISSUE THREAD

**Issue by v1nc3lx** [hankhank10/music-screen-api#15]
Testing @jjlawren devbranch: it seems everything's working fine but plex playing: skipping inside the same track shows the black screen until a new art is displayed.

**Comment by jjlawren** [comment]
I think I might know what's going on. Can you confirm you are using the new backlight control feature?

Edit: Looks like that doesn't matter, I think I see the problem.

**Comment by jjlawren** [comment]
@v1nc3lx can you try the latest updates to `dev`? I believe this should be fixed.

**Comment by v1nc3lx** [comment]
Yes, it is! :)
