### ISSUE TITLE
image quality on latest dev branch is poor

### ISSUE THREAD

**Issue by habra-cadabra** [hankhank10/music-screen-api#23]
hello!

updated to the latest dev build today and I noticed the image quality is poor when comparing to earlier versions. I rolled back the to the 799a2f2 build and the image looked better. 

the source isn't great in the example images, as Apple Music's supplied artwork for this album is only 400x400 pixels,
but you can see a difference between the two. I also noticed the default sonos.png file looked pixelated on the latest build. 

latest build:
<img width="744" alt="release-94cf788" src="https://user-images.githubusercontent.com/68568567/88698960-5c612e80-d0cc-11ea-85b7-0f13bc962f00.png">

799a2f2 build
<img width="736" alt="release-799a2f2" src="https://user-images.githubusercontent.com/68568567/88699075-7dc21a80-d0cc-11ea-86a6-0e776fa9d100.png">

(one final note, the only change I made to the file was to change the font size of the track title from 40 to 30)

**Comment by jjlawren** [comment]
Ah, I see why. I misread some library documentation and mistakenly switched to a lower quality resizing algorithm. Easy fix.

**Comment by jjlawren** [comment]
Should be fixed in ed1a358a8170a13dbb1598e1ec579f662f4c3657, let me know if it looks better.

**Comment by habra-cadabra** [comment]
look better! 

thanks so much for your continued work on this project, it's very cool.
