### ISSUE TITLE
Additional Sonos Info to display ...

### ISSUE THREAD

**Issue by jamesvcc** [hankhank10/music-screen-api#40]
I have this up and running in conjunction with an NFC reader to control tracks/volume/crossfade/shuffle etc....

I would like to display the current status of Volume/Shuffle & Crossfade as part of the additional information screen.

I am a real novice, how would I go about doing this.

Thanks,
James

**Comment by jamesvcc** [comment]
Hi, I know it is asking quite a bit, but can anyone help me with this.  I notice @jjlawren, you have made modifications so have the skill - can you help me?

**Comment by jjlawren** [comment]
Yes it's possible, but I won't have time to work on that for a while.

**Comment by ashenshugarRET** [comment]
I'm working to implement this. I'll post a pull request when ready.
This is now working and is implemented in pull request #59
![sonos-music-api Examples of Display Modes Show Play Settings](https://user-images.githubusercontent.com/42817877/154850750-267152c5-e370-4d4e-8737-0d66af96415e.png)
