### ISSUE TITLE
show_artist_and_album not behaving as expected 

### ISSUE THREAD

**Issue by habra-cadabra** [hankhank10/music-screen-api#46]
Hello! 

I’ve Noticed that the show_artist_and_album setting doesn’t seem to behave according to the description. 

When set to true the artist and album are displayed as expected. When set to false album title is still displayed. 

Perhaps this setting could have 4 values? Off, artist only, album only, album & artist?

This is an example set to false: 

![AB78D548-B1C0-4D8A-858B-DAFC395FF251](https://user-images.githubusercontent.com/68568567/96074314-fc2d8d80-0e6d-11eb-95c1-e1c7513cfafc.jpeg)

**Comment by hankhank10** [comment]
There are two settings:

`show_details` determines whether there is any detail shown at all. False shows just the album art, True shows some details.

The level of details displayed is determined by `show_artist_and_album`

I thought this was clear from the comment (Ignored if 'show_details' is False) but very open to ideas on how this could be clearer.

**Comment by jjlawren** [comment]
I thought it should only display the track name (not the album) with the settings you're using. 

What version of the script are you running and what's the media source?

**Comment by habra-cadabra** [comment]
@jjlawren yeah, that's what I would expect too. running the latest build 9e2f533. the source is Apple Music, Local Library and even some Amazon music. 

I know this isn't very helpful, but I've noticed this a few builds back. my wife and I had a baby early in September and haven't had a moment to report it until now. 

if I can get some time tonight, I can try and load up some legacy builds and see when this issue started.

**Comment by habra-cadabra** [comment]
ok, I was able to go back through some builds and pinpoint when the behavior changed. 

this is build b69d862 form Aug. 1, behaving as expected:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/68568567/96356925-ab5ea480-10ba-11eb-9a06-51b61863b0d7.png">

note the album or artist is not showing, however, there seems to be a weird glitch in the text in the 2nd line.

this is build 8861bfe from Aug. 3, when the behavior of the show_artist_and_album changed:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/68568567/96356960-00021f80-10bb-11eb-8801-3cb7325cead7.png">

note the album is showing, but not the artist.

**Comment by jjlawren** [comment]
Thanks for putting in the effort to track this down. Looks like it's probably related to my changes. I'll take a look as soon as I can.

**Comment by jjlawren** [comment]
@habra-cadabra I've created a PR to fix this. I don't remember why some of the checks existed in the code I replaced. Would you be able to validate a bit on that branch before we merge?

**Comment by habra-cadabra** [comment]
nice! I'll try and check this in the next day or so. thanks!

**Comment by habra-cadabra** [comment]
hey there, sorry for the delay!

running build c2aa8e4, and it looks good and works as expected. Thanks for sorting that out! much appreciated. 

<img width="743" alt="image" src="https://user-images.githubusercontent.com/68568567/99161931-3ed8c480-26bd-11eb-9dc5-013239fe07e4.png">
