### ISSUE TITLE
Optional info screen when Sonos is not in use

### ISSUE THREAD

**Issue by dnsdlx** [hankhank10/music-screen-api#52]
Hi Mark,

I hope that this the correct way to adress this topics via Github - I am sorry, a real beginner.

Thank you very much for this cool project. Shortly before Christmas I ordered a display from Pimoroni and received it in early January. I absolutely love the resolution and colors - we mounted it into a small square picture frame standing aside other frames with "real" pictures.

But there is one big question: As long as the Sonos system is not active the screen stays black and unused. I am very happy that the screen is really off at that time BUT a big improvement for many users might be an option to show a kind of info screen during the times Sonos is off.

Unfortunately I do not have any experience with code but I would like to ask how much work it would be to provide such an option - in case other users are interested in this too? An idea could be to call a definable URL which could then provide weather info, daytime or appointments. Would be a fantastic tool!

Would be great to have your feedback on this, all the best for 2021!
Dennis

**Comment by hankhank10** [comment]
Hi Dennis,

Thanks for raising this.

I have considered in the past adding other information (eg a clock) but decided to keep this simple and focused at the moment. There are probably as many different options as to what people would want displayed here as there are users.

If others were keen to build this I would be delighted to see it in use. I would encourage you to learn python for exactly this purpose! There's a code sample on how to build a clock here: https://www.reddit.com/r/raspberry_pi/comments/5gcu6l/full_screen_clock_tkinter_example/

Good luck! I will be closing this issue for now as I don't propose to incorporate additional features into the main repo at this time.
